export const groupFields = [
  { id: "nazwa", label: "Nazwa", type: "text", name: "nazwa", checked: true },
  { id: "zglaszac", label: "Zgłaszać", type: "checkbox", name: "zglaszac" },
  {
    id: "weryfikowac",
    label: "Weryfikować",
    type: "checkbox",
    name: "weryfikowac",
  },
  { id: "zamawiac", label: "Zamawiać", type: "checkbox", name: "zamawiac" },
  {
    id: "01_wyswietlanie",
    label: "01 - Wyświetlanie",
    type: "checkbox",
    name: "01_wyswietlanie",
  },
  {
    id: "01_dodawanie",
    label: "01 - Dodawanie",
    type: "checkbox",
    name: "01_dodawanie",
  },
  {
    id: "01_edycja",
    label: "01 - Edycja",
    type: "checkbox",
    name: "01_edycja",
  },
  {
    id: "02_dodawanie",
    label: "02 - Dodawanie",
    type: "checkbox",
    name: "02_dodawanie",
  },
  {
    id: "02_edycja",
    label: "02 - Edycja",
    type: "checkbox",
    name: "02_edycja",
  },
  {
    id: "02_wyswietlanie",
    label: "02 - Wyświetlanie",
    type: "checkbox",
    name: "02_wyswietlanie",
  },
  {
    id: "03_dodawanie",
    label: "03 - Dodawanie",
    type: "checkbox",
    name: "03_dodawanie",
  },
  {
    id: "03_edycja",
    label: "03 - Edycja",
    type: "checkbox",
    name: "03_edycja",
  },
  {
    id: "03_wyswietlanie",
    label: "03 - Wyświetlanie",
    type: "checkbox",
    name: "03_wyswietlanie",
  },
  {
    id: "04_dodawanie",
    label: "04 - Dodawanie",
    type: "checkbox",
    name: "04_dodawanie",
  },
  {
    id: "04_edycja",
    label: "04 - Edycja",
    type: "checkbox",
    name: "04_edycja",
  },
  {
    id: "04_wyswietlanie",
    label: "04 - Wyświetlanie",
    type: "checkbox",
    name: "04_wyswietlanie",
  },
  {
    id: "05_dodawanie",
    label: "05 - Dodawanie",
    type: "checkbox",
    name: "05_dodawanie",
  },
  {
    id: "05_edycja",
    label: "05 - Edycja",
    type: "checkbox",
    name: "05_edycja",
  },
  {
    id: "05_wyswietlanie",
    label: "05 - Wyświetlanie",
    type: "checkbox",
    name: "05_wyswietlanie",
  },
  {
    id: "06_dodawanie",
    label: "06 - Dodawanie",
    type: "checkbox",
    name: "06_dodawanie",
  },
  {
    id: "06_edycja",
    label: "06 - Edycja",
    type: "checkbox",
    name: "06_edycja",
  },
  {
    id: "06_wyswietlanie",
    label: "06 - Wyświetlanie",
    type: "checkbox",
    name: "06_wyswietlanie",
  },
  {
    id: "07_dodawanie",
    label: "07 - Dodawanie",
    type: "checkbox",
    name: "07_dodawanie",
  },
  {
    id: "07_edycja",
    label: "07 - Edycja",
    type: "checkbox",
    name: "07_edycja",
  },
  {
    id: "07_wyswietlanie",
    label: "07 - Wyświetlanie",
    type: "checkbox",
    name: "07_wyswietlanie",
  },
  {
    id: "08_dodawanie",
    label: "08 - Dodawanie",
    type: "checkbox",
    name: "08_dodawanie",
  },
  {
    id: "08_edycja",
    label: "08 - Edycja",
    type: "checkbox",
    name: "08_edycja",
  },
  {
    id: "08_wyswietlanie",
    label: "08 - Wyświetlanie",
    type: "checkbox",
    name: "08_wyswietlanie",
  },
  {
    id: "09_dodawanie",
    label: "09 - Dodawanie",
    type: "checkbox",
    name: "09_dodawanie",
  },
  {
    id: "09_edycja",
    label: "09 - Edycja",
    type: "checkbox",
    name: "09_edycja",
  },
  {
    id: "09_wyswietlanie",
    label: "09 - Wyświetlanie",
    type: "checkbox",
    name: "09_wyswietlanie",
  },
  {
    id: "user_dodawanie",
    label: "User - Dodawanie",
    type: "checkbox",
    name: "user_dodawanie",
  },
  {
    id: "user_usuwanie",
    label: "User - Usuwanie",
    type: "checkbox",
    name: "user_usuwanie",
  },
  {
    id: "user_wyswietlanie",
    label: "User - Wyświetlanie",
    type: "checkbox",
    name: "user_wyswietlanie",
  },
  {
    id: "objekt_dodawanie",
    label: "Obiekt - Dodawanie",
    type: "checkbox",
    name: "objekt_dodawanie",
  },
  {
    id: "objekt_usuwanie",
    label: "Obiekt - Usuwanie",
    type: "checkbox",
    name: "objekt_usuwanie",
  },
  {
    id: "objekt_edycja",
    label: "Obiekt - Edycja",
    type: "checkbox",
    name: "objekt_edycja",
  },
];
