export const nvrFields = [
  { id: "nrSeryjny", label: "Nr Seryjny", type: "text", name: "nr_seryjny" },
  { id: "model", label: "Model", type: "text", name: "model" },
  { id: "mac", label: "MAC", type: "text", name: "mac" },
  {
    id: "uprawnienia",
    label: "Uprawnienia",
    type: "checkbox",
    name: "podzial_uprawnien",
  },
  { id: "modelDysku", label: "Model Dysku", type: "text", name: "model_dysku" },
  {
    id: "wielkoscDysku",
    label: "Wielkość Dysku",
    type: "number",
    name: "wielkoscDysku",
  },
  {
    id: "dataWymianyDysku",
    label: "Data Wymiany Dysku",
    type: "date",
    name: "dataWymianyDysku",
  },
  { id: "portHTTP", label: "Port HTTP", type: "number", name: "portHTTP" },
  { id: "portDANE", label: "Port DANE", type: "number", name: "portDANE" },
  {
    id: "iloscKamer",
    label: "Ilość Kamer",
    type: "number",
    name: "iloscKamer",
  },
  {
    id: "ipWewnetrzne",
    label: "IP Wewnętrzne",
    type: "text",
    name: "ipWewnetrzne",
  },
  {
    id: "ipZewnetrzne",
    label: "IP Zewnętrzne",
    type: "text",
    name: "ipZewnetrzne",
  },
  { id: "p2p", label: "P2P", type: "checkbox", name: "p2p" },
  { id: "uwagi", label: "Uwagi", type: "text", name: "uwagi" },
  { id: "notatki", label: "Notatki", type: "text", name: "notatki" },
  { id: "dataOD", label: "Data OD", type: "date", name: "dataOD" },
];
