export const objectFileds = [
  { id: "nazwa", label: "Nazwa", type: "text", name: "nazwa", value: "" },
  {
    id: "kod_pocztowy",
    label: "Kod Pocztowy",
    type: "text",
    name: "kod_pocztowy",
    value: "",
  },
  {
    id: "miejscowosc",
    label: "Miejscowość",
    type: "text",
    name: "miejscowosc",
    value: "",
  },
  { id: "ul", label: "Ulica", type: "text", name: "ul", value: "" },
  {
    id: "nr_budynku",
    label: "Numer Budynku",
    type: "text",
    name: "nr_budynku",
    value: "",
  },
  {
    id: "nr_lokalu",
    label: "Numer Lokalu",
    type: "text",
    name: "nr_lokalu",
    value: "",
  },
  { id: "pietro", label: "Piętro", type: "text", name: "pietro", value: "" },
  {
    id: "kod_domofonu",
    label: "Kod Domofonu",
    type: "text",
    name: "kod_domofonu",
    value: "",
  },
  {
    id: "szerokosc_g",
    label: "Szerokość Geograficzna",
    type: "number",
    name: "szerokosc_g",
    value: 0,
  },
  {
    id: "dlugosc_g",
    label: "Długość Geograficzna",
    type: "number",
    name: "dlugosc_g",
    value: 0,
  },
  {
    id: "dataOD",
    label: "Data OD",
    type: "date",
    name: "dataOD",
    value: new Date().toISOString().split("T")[0],
  },
  {
    id: "klient_wlasny",
    label: "Klient Własny",
    type: "checkbox",
    name: "klient_wlasny",
    value: false,
  },
  {
    id: "przekazany_p",
    label: "Przekazany Personel",
    type: "text",
    name: "przekazany_p",
    value: "",
  },
  { id: "uwagi", label: "Uwagi", type: "text", name: "uwagi", value: "" },
];
