export const PCFields = [
  { id: "nrSeryjny", label: "Nr Seryjny", type: "text", name: "nr_seryjny" },
  {
    id: "podzialUprawnien",
    label: "Podział Uprawnień",
    type: "checkbox",
    name: "podzial_uprawnien",
  },
  {
    id: "systemOperacyjny",
    label: "System Operacyjny",
    type: "text",
    name: "system_operacyjny",
  },
  {
    id: "rodzajDysku",
    label: "Rodzaj Dysku",
    type: "text",
    name: "rodzaj_dysku",
  },
  {
    id: "dataWymianyDysku",
    label: "Data Wymiany Dysku",
    type: "date",
    name: "data_wymiany_dysku",
  },
  { id: "ram", label: "RAM (GB)", type: "number", name: "ram" },
  {
    id: "kartaGraficzna",
    label: "Karta Graficzna (0 - Zintegrowana, 1 - Dedykowana)",
    type: "checkbox",
    name: "karta_graficzna",
  },
  {
    id: "plytaGlowna",
    label: "Płyta Główna",
    type: "text",
    name: "plyta_glowna",
  },
  { id: "zasilacz", label: "Zasilacz", type: "text", name: "zasilacz" },
  {
    id: "programZdalny",
    label: "Program Zdalny",
    type: "text",
    name: "program_zdalny",
  },
  { id: "idProgramu", label: "ID Programu", type: "text", name: "id_programu" },
  { id: "uwagi", label: "Uwagi", type: "text", name: "uwagi" },
  { id: "notatki", label: "Notatki", type: "text", name: "notatki" },
  { id: "dataOd", label: "Data Od", type: "date", name: "data_od" },
  { id: "dataDo", label: "Data Do", type: "date", name: "data_do" },
];
