const { addRecord } = require("../controllers/itemController");

const addGroup = (req, res) => {
  const {
    nazwa,
    zglaszac,
    weryfikowac,
    zamawiac,
    "01_wyswietlanie": wyswietlanie_01,
    "01_dodawanie": dodawanie_01,
    "01_edycja": edycja_01,
    "02_dodawanie": dodawanie_02,
    "02_edycja": edycja_02,
    "02_wyswietlanie": wyswietlanie_02,
    "03_dodawanie": dodawanie_03,
    "03_edycja": edycja_03,
    "03_wyswietlanie": wyswietlanie_03,
    "04_dodawanie": dodawanie_04,
    "04_edycja": edycja_04,
    "04_wyswietlanie": wyswietlanie_04,
    "05_dodawanie": dodawanie_05,
    "05_edycja": edycja_05,
    "05_wyswietlanie": wyswietlanie_05,
    "06_dodawanie": dodawanie_06,
    "06_edycja": edycja_06,
    "06_wyswietlanie": wyswietlanie_06,
    "07_dodawanie": dodawanie_07,
    "07_edycja": edycja_07,
    "07_wyswietlanie": wyswietlanie_07,
    "08_dodawanie": dodawanie_08,
    "08_edycja": edycja_08,
    "08_wyswietlanie": wyswietlanie_08,
    "09_dodawanie": dodawanie_09,
    "09_edycja": edycja_09,
    "09_wyswietlanie": wyswietlanie_09,
    user_dodawanie,
    user_usuwanie,
    user_wyswietlanie,
    objekt_dodawanie,
    objekt_usuwanie,
    objekt_edycja,
  } = req.body;

  const columns = [
    "nazwa",
    "zglaszac",
    "weryfikowac",
    "zamawiac",
    "01_wyswietlanie",
    "01_dodawanie",
    "01_edycja",
    "02_dodawanie",
    "02_edycja",
    "02_wyswietlanie",
    "03_dodawanie",
    "03_edycja",
    "03_wyswietlanie",
    "04_dodawanie",
    "04_edycja",
    "04_wyswietlanie",
    "05_dodawanie",
    "05_edycja",
    "05_wyswietlanie",
    "06_dodawanie",
    "06_edycja",
    "06_wyswietlanie",
    "07_dodawanie",
    "07_edycja",
    "07_wyswietlanie",
    "08_dodawanie",
    "08_edycja",
    "08_wyswietlanie",
    "09_dodawanie",
    "09_edycja",
    "09_wyswietlanie",
    "user_dodawanie",
    "user_usuwanie",
    "user_wyswietlanie",
    "objekt_dodawanie",
    "objekt_usuwanie",
    "objekt_edycja",
  ];

  const values = [
    nazwa,
    zglaszac || 0,
    weryfikowac || 0,
    zamawiac || 0,
    wyswietlanie_01 || 0,
    dodawanie_01 || 0,
    edycja_01 || 0,
    dodawanie_02 || 0,
    edycja_02 || 0,
    wyswietlanie_02 || 0,
    dodawanie_03 || 0,
    edycja_03 || 0,
    wyswietlanie_03 || 0,
    dodawanie_04 || 0,
    edycja_04 || 0,
    wyswietlanie_04 || 0,
    dodawanie_05 || 0,
    edycja_05 || 0,
    wyswietlanie_05 || 0,
    dodawanie_06 || 0,
    edycja_06 || 0,
    wyswietlanie_06 || 0,
    dodawanie_07 || 0,
    edycja_07 || 0,
    wyswietlanie_07 || 0,
    dodawanie_08 || 0,
    edycja_08 || 0,
    wyswietlanie_08 || 0,
    dodawanie_09 || 0,
    edycja_09 || 0,
    wyswietlanie_09 || 0,
    user_dodawanie || 0,
    user_usuwanie || 0,
    user_wyswietlanie || 0,
    objekt_dodawanie || 0,
    objekt_usuwanie || 0,
    objekt_edycja || 0,
  ];

  addRecord("grupy", columns, values, res);
};

module.exports = {
  addGroup,
};
